services:
  - type: web
    name: meu-fastapi
    env: python
    plan: free
    runtime: python-3.12.4
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
